-- function StartFloatingWindow(title)
--   local width = vim.api.nvim_get_option('columns')
--   local height = vim.api.nvim_get_option('lines')
--   local win_height = math.ceil(height * 3/4)
--   local win_width = math.ceil(width * 0.7)
--
--
--   local buf = vim.api.nvim_create_buf(false, true)
--   local opts = {
--     relative = "editor",
--     anchor = "NW",
--     width = win_width,
--     height = win_height,
--     row = math.ceil((height - win_height)/2),
--     col = math.ceil((width - win_width)/2),
--     border = 'rounded',
--     title = title,
--     title_pos = 'left'
--   }
--
--   local win = vim.api.nvim_open_win(buf, true, opts)
-- end
