-- return {
-- 	'romgrk/barbar.nvim',
-- 	dependencies = {
-- 		'nvim-tree/nvim-web-devicons'
-- 	},
-- 	init = function() vim.g.barbar_auto_setup = false end,
-- 	opts = {
-- 	},
-- 	keys = {
-- 		{'<S-h>', '<cmd>tabprevious<cr>', 'n'},
-- 		{'<S-l>', '<cmd>tabnext<cr>', 'n'},
-- 	}
-- }
--
--
return {}
